version: '3'
services:
  openai-whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest
    environment:
      ASR_MODEL: ${ASR_MODEL}
      ASR_ENGINE: ${ASR_ENGINE}
    env_file:
      - .env
    ports:
      - "9000:9000"
    #networks:
    #  - batchstt

#networks:
#  batchstt: